<?php  //[STAMP] 25702ebd0e252a400f95b17934c1ec61
namespace execut\javascriptHandler\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

trait UnitTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
